gui:
  showBottomLine: true
  showCommandLog: false
  showFileTree: false
  showRandomTip: false
  theme:
    selectedLineBgColor:
      - default
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --line-numbers
